### ISSUE TITLE
Console Log needed?

### ISSUE THREAD

**Issue by kohfuchs** [Maetran/ausserfernnerds_website#5]
Hi, 
Just want make sure that this Line of Code ist needed.
Whats the point of console logging the data bevor printing it out?

https://github.com/Maetran/ausserfernnerds_website/blob/41aceac68f70cb7a33c2df723f97eed32f160281/piholelists.html#L68

**Comment by Maetran** [comment]
thanks for the hint. 
deleted the console.log lines (2x)
